### ISSUE TITLE
pt 下载文件名会被jproxy重命名导致转移下载客户端后需要重新下

### ISSUE THREAD

**Issue by whetherTsmile** [LuckyPuppy514/jproxy#113]
**部署环境（windows / docker）**

docker

**问题描述**

即使pt索引器url 未通过jproxy代理,  pt 下载的文件名还是会被jproxy重命名导致转移下载客户端后,因为文件名不同需要重新下载

```
11:12:29.167 ERROR [xec-7] org.apache.juli.logging.DirectJDKLog.log(DirectJDKLog.java:175)                  : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception
org.springframework.web.client.HttpClientErrorException$TooManyRequests: 429 Too Many Requests: "<?xml version="1.0" encoding="UTF-8"?><EOL><error code="429" description="Indexer is disabled till 07/29/2024 11:17:29 due to recent failures." />"
        at org.springframework.web.client.HttpClientErrorException.create(HttpClientErrorException.java:130) ~[spring-web-6.0.7.jar:6.0.7]
        at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:183) ~[spring-web-6.0.7.jar:6.0.7]
        at org.springframework.web.client.ExtractingResponseErrorHandler.handleError(ExtractingResponseErrorHandler.java:148) ~[spring-web-6.0.7.jar:6.0.7]
        at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:137) ~[spring-web-6.0.7.jar:6.0.7]
        at org.springframework.web.client.ResponseErrorHandler.handleError(ResponseErrorHandler.java:63) ~[spring-web-6.0.7.jar:6.0.7]
        at org.springframework.web.client.RestTemplate.handleResponse(RestTemplate.java:915) ~[spring-web-6.0.7.jar:6.0.7]
        at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:864) ~[spring-web-6.0.7.jar:6.0.7]
        at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:764) ~[spring-web-6.0.7.jar:6.0.7]
        at org.springframework.web.client.RestTemplate.getForEntity(RestTemplate.java:405) ~[spring-web-6.0.7.jar:6.0.7]
        at com.lckp.jproxy.service.impl.IndexerServiceImpl.executeNewRequest(IndexerServiceImpl.java:164) ~[classes/:3.4.5]
        at jdk.internal.reflect.GeneratedMethodAccessor59.invoke(Unknown Source) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
        at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:343) ~[spring-aop-6.0.7.jar:6.0.7]
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:698) ~[spring-aop-6.0.7.jar:6.0.7]
        at com.lckp.jproxy.service.impl.SonarrProwlarrServiceImpl$$SpringCGLIB$$0.executeNewRequest(<generated>) ~[classes/:3.4.5]
        at com.lckp.jproxy.filter.IndexerFilter.doFilter(IndexerFilter.java:113) ~[classes/:3.4.5]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174) ~[tomcat-embed-core-10.1.7.jar:10.1.7]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149) ~[tomcat-embed-core-10.1.7.jar:10.1.7]
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:166) ~[tomcat-embed-core-10.1.7.jar:10.1.7]
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90) ~[tomcat-embed-core-10.1.7.jar:10.1.7]
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:493) ~[tomcat-embed-core-10.1.7.jar:10.1.7]
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:115) ~[tomcat-embed-core-10.1.7.jar:10.1.7]
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93) ~[tomcat-embed-core-10.1.7.jar:10.1.7]
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74) ~[tomcat-embed-core-10.1.7.jar:10.1.7]
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:341) ~[tomcat-embed-core-10.1.7.jar:10.1.7]
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:390) ~[tomcat-embed-core-10.1.7.jar:10.1.7]
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63) ~[tomcat-embed-core-10.1.7.jar:10.1.7]
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:894) ~[tomcat-embed-core-10.1.7.jar:10.1.7]
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1741) ~[tomcat-embed-core-10.1.7.jar:10.1.7]
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52) ~[tomcat-embed-core-10.1.7.jar:10.1.7]
        at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191) ~[tomcat-embed-core-10.1.7.jar:10.1.7]
        at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659) ~[tomcat-embed-core-10.1.7.jar:10.1.7]
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) ~[tomcat-embed-core-10.1.7.jar:10.1.7]
        at java.lang.Thread.run(Unknown Source) ~[?:?]
11:30:00.149 INFO  [ing-1] jproxy.service.impl.RadarrTitleServiceImpl.sync(RadarrTitleServiceImpl.java:173) : 同步电影标题成功：549
11:52:00.047 INFO  [ing-1] com.lckp.jproxy.task.SonarrRenameTask.lambda$run$0(SonarrRenameTask.java:169)    : qBittorrent 文件重命名成功：House.Of.The.Dragon.S02E07.2024.2160p.MAX.WEB-DL.x265.DV.HDR.DDP5.1.Atmos-ADWeb.mkv => S2E7.mkv
11:52:00.047 INFO  [ing-1] com.lckp.jproxy.task.SonarrRenameTask.lambda$run$0(SonarrRenameTask.java:173)    : qBittorrent 种子重命名成功：206ebbed7d45219dc1beb2c202d6a457e3e1be7f => House Of The Dragon S02E07 2024 2160p MAX WEB-DL x265 DV HDR DDP5.1 Atmos-ADWeb
12:00:00.616 INFO  [ing-1] jproxy.service.impl.SonarrTitleServiceImpl.sync(SonarrTitleServiceImpl.java:150) : 同步剧集标题成功：371
12:00:01.065 INFO  [ing-1] ckp.jproxy.service.impl.TmdbTitleServiceImpl.sync(TmdbTitleServiceImpl.java:127) : 同步剧集标题成功：0
12:22:30.015 INFO  [ing-1] com.lckp.jproxy.task.SonarrRenameTask.lambda$run$0(SonarrRenameTask.java:169)    : qBittorrent 文件重命名成功：House.Of.The.Dragon.S02E04.2024.2160p.MAX.WEB-DL.x265.DV.HDR.DDP5.1.Atmos-ADWeb.mkv => S2E4.mkv
12:22:30.015 INFO  [ing-1] com.lckp.jproxy.task.SonarrRenameTask.lambda$run$0(SonarrRenameTask.java:173)    : qBittorrent 种子重命名成功：4fb124bcff6927aa6d4fc6a3e1f4bea8ab35f586 => House Of The Dragon S02E04 2024 2160p MAX WEB-DL x265 DV HDR DDP5.1 Atmos-ADWeb
12:22:30.024 INFO  [ing-1] com.lckp.jproxy.task.SonarrRenameTask.lambda$run$0(SonarrRenameTask.java:169)    : qBittorrent 文件重命名成功：House.Of.The.Dragon.S02E05.2024.2160p.MAX.WEB-DL.x265.DV.HDR.DDP5.1.Atmos-ADWeb.mkv => S2E5.mkv
12:22:30.025 INFO  [ing-1] com.lckp.jproxy.task.SonarrRenameTask.lambda$run$0(SonarrRenameTask.java:173)    : qBittorrent 种子重命名成功：f1751a776635ae8469aa72124f38a13f136643d2 => House Of The Dragon S02E05 2024 2160p MAX WEB-DL x265 DV HDR DDP5.1 Atmos-ADWeb
12:30:00.293 INFO  [ing-1] jproxy.service.impl.RadarrTitleServiceImpl.sync(RadarrTitleServiceImpl.java:173) : 同步电影标题成功：549
13:00:00.381 INFO  [ing-1] jproxy.service.impl.SonarrTitleServiceImpl.sync(SonarrTitleServiceImpl.java:150) : 同步剧集标题成功：371
13:00:00.988 INFO  [ing-1] ckp.jproxy.service.impl.TmdbTitleServiceImpl.sync(TmdbTitleServiceImpl.java:127) : 同步剧集标题成功：0
```

**相关截图**
这是pt站点索引器配置
![image](https://github.com/user-attachments/assets/56ef82f5-ca48-42db-938e-2aae5f8765f0)
抓取记录
![image](https://github.com/user-attachments/assets/5b665a92-8815-4d60-939b-9fab3c177614)
![image](https://github.com/user-attachments/assets/b6d6088f-145d-404a-a9da-efcc08909dd2)

**Comment by whetherTsmile** [comment]
=-=突然想明白了,重命名是在下载客户端重命名的

**Comment by whetherTsmile** [comment]
大佬有没有办法,让qibittorrent根据tag来选择是否重命名

**Comment by LuckyPuppy514** [comment]
> 大佬有没有办法,让qibittorrent根据tag来选择是否重命名

有办法，但是得开发，但是感觉可以不用，因为不走 JProxy 的下载，即使重命名也是重命名成原始名称，应该不影响才对

**Comment by whetherTsmile** [comment]
> qBittorrent 文件重命名成功：House.Of.The.Dragon.S02E04.2024.2160p.MAX.WEB-DL.x265.DV.HDR.DDP5.1.Atmos-ADWeb.mkv => S2E4.mkv

但是你看我这几个种子qBittorrent 文件重命名成功：House.Of.The.Dragon.S02E04.2024.2160p.MAX.WEB-DL.x265.DV.HDR.DDP5.1.Atmos-ADWeb.mkv => S2E4.mkv， 他是重命名成SE的格式了
