### ISSUE TITLE
Sonarr的代理如何设置？

### ISSUE THREAD

**Issue by Sandrock02** [LuckyPuppy514/jproxy#4]
我安装了Prowlarr作为Indexer聚合工具，在Sonarr里URL是这样的：
```
http://192.168.2.12:9696/6/
```
![image](https://user-images.githubusercontent.com/4281207/182028132-86c70bbe-0df0-4cde-8a16-88ca6869c3bb.png)

我的JProxy是安装在同一台NAS上，所以我改成
```
http://192.168.2.12:8117/6/
```
但是测试失败。
这个要怎么设置呢？

**Comment by LuckyPuppy514** [comment]
点击测试的时候，看看你的prowlarr日志有没有请求过去

**Comment by LuckyPuppy514** [comment]
因为我用的 jackett，所有没注意 prowlarr，我试了下，有个小问题，等我发新版本吧

**Comment by Sandrock02** [comment]
我的Prowlarr WebUI都进不去了。LOG为：
```
[Info] Prowlarr.Http.Authentication.ApiKeyAuthenticationHandler: AuthenticationScheme: API was challenged. 
```

**Comment by LuckyPuppy514** [comment]
你的 prowlarr 进不去我就不知道咋回事了，你可以重启试试
不过 jproxy 配置有问题，导致不会转发 prowlarr，我晚点发个版本

**Comment by LuckyPuppy514** [comment]
已经发布新版本了，麻烦有空重新试试

**Comment by Sandrock02** [comment]
我试了2.5.2，但是还是不行。以下是JProxy的log：
```
reactor.core.Exceptions$ReactiveException: io.netty.handler.ssl.SslHandshakeTimeoutException: handshake timed out after 10000ms
	at reactor.core.Exceptions.propagate(Exceptions.java:393)
	at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:97)
	at reactor.core.publisher.Mono.block(Mono.java:1679)
	at com.lckp.controller.PageController.notice(PageController.java:125)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:190)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:138)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:105)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:879)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:793)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1040)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:943)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:898)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:634)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.github.xiaoymin.knife4j.spring.filter.ProductionSecurityFilter.doFilter(ProductionSecurityFilter.java:45)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.github.xiaoymin.knife4j.spring.filter.SecurityBasicAuthFilter.doFilter(SecurityBasicAuthFilter.java:87)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:373)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1590)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
	Suppressed: java.lang.Exception: #block terminated with an error
		at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:99)
		... 58 common frames omitted
Caused by: io.netty.handler.ssl.SslHandshakeTimeoutException: handshake timed out after 10000ms
	at io.netty.handler.ssl.SslHandler$5.run(SslHandler.java:2054)
	Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException: 
Error has been observed at the following site(s):
	|_ checkpoint ⇢ Request to GET https://raw.githubusercontent.com/LuckyPuppy514/jproxy/main/src/main/resources/json/notice.json [DefaultWebClient]

Stack trace:
		at io.netty.handler.ssl.SslHandler$5.run(SslHandler.java:2054)
		at io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98)
		at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:170)
		at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
		at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
		at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:384)
		at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
		at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
		at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
		at java.lang.Thread.run(Thread.java:748)
2022-08-01 21:25:25.665  WARN 9 --- [or-http-epoll-1] r.netty.http.client.HttpClientConnect    : [id: 0xf529a750, L:/192.168.2.12:43256 - R:raw.githubusercontent.com/185.199.111.133:443] The connection observed an error
io.netty.handler.ssl.SslHandshakeTimeoutException: handshake timed out after 10000ms
	at io.netty.handler.ssl.SslHandler$5.run(SslHandler.java:2054)
	Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException: 
Error has been observed at the following site(s):
	|_ checkpoint ⇢ Request to GET https://raw.githubusercontent.com/LuckyPuppy514/jproxy/main/src/main/resources/json/notice.json [DefaultWebClient]

Stack trace:
		at io.netty.handler.ssl.SslHandler$5.run(SslHandler.java:2054)
		at io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98)
		at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:170)
		at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
		at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
		at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:384)
		at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
		at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
		at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
```
针对我这种情况，需要更改代理路径吗？比如改成`.*/\d+/.*`

**Comment by LuckyPuppy514** [comment]
这个错误应该不影响才对，这个是到github取更新日志的

**Comment by LuckyPuppy514** [comment]
webui进不去么

**Comment by Sandrock02** [comment]
WebUI可以进去，但是我测试Sonnar的indexer的时候，貌似也没有看到JProxy里有log产生，所以它接收到请求了吗？

**Comment by LuckyPuppy514** [comment]
你sonarr配置改了吗

**Comment by LuckyPuppy514** [comment]
新版应该有日志了，我刚刚加了，原来是debug日志，所以看不到

**Comment by LuckyPuppy514** [comment]
![image](https://user-images.githubusercontent.com/53246532/182160084-ee231690-31d2-417b-9f0f-0e41d4b61519.png)

**Comment by Sandrock02** [comment]
改了，就改了个端口号，从9696改成了8117，所以URL看起来是这样的：
![image](https://user-images.githubusercontent.com/4281207/182160175-453123e4-8f2a-487f-9ca9-f28cec5366d7.png)

```
2022-08-01 21:35:36.3|Warn|Torznab|Unable to connect to indexer

[v3.0.8.1507] System.Xml.XmlException: The 'link' start tag on line 13 position 3 does not match the end tag of 'head'. Line 164, position 3.
  at System.Xml.XmlTextReaderImpl.Throw (System.Exception e) [0x00027] in <7ff8f64b3a334d14838f500f5ad27e36>:0 
  at System.Xml.XmlTextReaderImpl.Throw (System.String res, System.String[] args) [0x00029] in <7ff8f64b3a334d14838f500f5ad27e36>:0 
  at System.Xml.XmlTextReaderImpl.ThrowTagMismatch (System.Xml.XmlTextReaderImpl+NodeData startTag) [0x00086] in <7ff8f64b3a334d14838f500f5ad27e36>:0 
  at System.Xml.XmlTextReaderImpl.ParseEndElement () [0x00085] in <7ff8f64b3a334d14838f500f5ad27e36>:0 
  at System.Xml.XmlTextReaderImpl.ParseElementContent () [0x00149] in <7ff8f64b3a334d14838f500f5ad27e36>:0 
  at System.Xml.XmlTextReaderImpl.Read () [0x00085] in <7ff8f64b3a334d14838f500f5ad27e36>:0 
  at System.Xml.Linq.XContainer.ReadContentFrom (System.Xml.XmlReader r) [0x00025] in <8d6554d17b084e8689fdd20da40c74a1>:0 
  at System.Xml.Linq.XContainer.ReadContentFrom (System.Xml.XmlReader r, System.Xml.Linq.LoadOptions o) [0x00005] in <8d6554d17b084e8689fdd20da40c74a1>:0 
  at System.Xml.Linq.XDocument.Load (System.Xml.XmlReader reader, System.Xml.Linq.LoadOptions options) [0x00024] in <8d6554d17b084e8689fdd20da40c74a1>:0 
  at System.Xml.Linq.XDocument.Parse (System.String text, System.Xml.Linq.LoadOptions options) [0x00016] in <8d6554d17b084e8689fdd20da40c74a1>:0 
  at System.Xml.Linq.XDocument.Parse (System.String text) [0x00000] in <8d6554d17b084e8689fdd20da40c74a1>:0 
  at NzbDrone.Core.Indexers.Newznab.NewznabCapabilitiesProvider.ParseCapabilities (NzbDrone.Common.Http.HttpResponse response) [0x00006] in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\Indexers\Newznab\NewznabCapabilitiesProvider.cs:92 
  at NzbDrone.Core.Indexers.Newznab.NewznabCapabilitiesProvider.FetchCapabilities (NzbDrone.Core.Indexers.Newznab.NewznabSettings indexerSettings) [0x00100] in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\Indexers\Newznab\NewznabCapabilitiesProvider.cs:76 
  at NzbDrone.Core.Indexers.Newznab.NewznabCapabilitiesProvider+<>c__DisplayClass4_0.<GetCapabilities>b__0 () [0x00000] in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\Indexers\Newznab\NewznabCapabilitiesProvider.cs:36 
  at NzbDrone.Common.Cache.Cached`1[T].Get (System.String key, System.Func`1[TResult] function, System.Nullable`1[T] lifeTime) [0x000b1] in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Common\Cache\Cached.cs:104 
  at NzbDrone.Core.Indexers.Newznab.NewznabCapabilitiesProvider.GetCapabilities (NzbDrone.Core.Indexers.Newznab.NewznabSettings indexerSettings) [0x00020] in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\Indexers\Newznab\NewznabCapabilitiesProvider.cs:36 
  at NzbDrone.Core.Indexers.Torznab.Torznab.get_PageSize () [0x00000] in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\Indexers\Torznab\Torznab.cs:23 
  at NzbDrone.Core.Indexers.Torznab.Torznab.GetRequestGenerator () [0x00000] in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\Indexers\Torznab\Torznab.cs:27 
  at NzbDrone.Core.Indexers.HttpIndexerBase`1[TSettings].TestConnection () [0x00007] in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\Indexers\HttpIndexerBase.cs:336 

2022-08-01 21:35:36.3|Warn|SonarrErrorPipeline|Invalid request Validation failed: 
 -- : Unable to connect to indexer, check the log for more details
```

**Comment by LuckyPuppy514** [comment]
你这个是sonarr的日志吧，这个错误应该不是jproxy引起的

**Comment by Sandrock02** [comment]
JProxy那里没有log产生，就像点击Test后就没有发请求，或者请求没有被JProxy处理。

**Comment by LuckyPuppy514** [comment]
你要方便，我远程帮你看看

**Comment by jassysth** [comment]
我也是这两天更新版本后突然用不了了，也是prowlarr

**Comment by LuckyPuppy514** [comment]
删除掉数据库/config/sqlite.db，然后升级到v2.5.2

**Comment by LuckyPuppy514** [comment]
原来有个bug，默认配置也错了，今天刚发布的

**Comment by LuckyPuppy514** [comment]
还有问题也可以加我QQ

**Comment by LuckyPuppy514** [comment]
> 我也是这两天更新版本后突然用不了了，也是prowlarr

现在可以了吗？

**Comment by LuckyPuppy514** [comment]
> 我也是这两天更新版本后突然用不了了，也是prowlarr

原来这个问题已经解决了，我先关闭了。有问题 QQ 联系，或者单独提个 ISSUE
