### ISSUE TITLE
無法連通到Radarr

### ISSUE THREAD

**Issue by xiNeRoar** [LuckyPuppy514/jproxy#58]
**部署环境（windows / docker）**

docker
Radarr版本: 4.6.4.7568-ls183 (Linuxserver鏡像)
Jproxy版本: 3.3.8

**问题描述**
 
無法連通到radarr

![image](https://github.com/LuckyPuppy514/jproxy/assets/66216186/7f50abbb-30e0-48a8-80a4-f75168aa123f)
![image](https://github.com/LuckyPuppy514/jproxy/assets/66216186/ec0649bd-3f5b-4bb1-a421-e69a79ffe86b)

[v4.6.4.7568] System.Xml.XmlException: 'doctype' is an unexpected token. The expected token is 'DOCTYPE'. Line 1, position 3.
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.Throw(String res, String[] args)
   at System.Xml.XmlTextReaderImpl.ThrowUnexpectedToken(String expectedToken1, String expectedToken2)
   at System.Xml.XmlTextReaderImpl.ParseDoctypeDecl()
   at System.Xml.XmlTextReaderImpl.ParseDocumentContent()
   at System.Xml.Linq.XDocument.Load(XmlReader reader, LoadOptions options)
   at System.Xml.Linq.XDocument.Parse(String text, LoadOptions options)
   at NzbDrone.Core.Indexers.Newznab.NewznabCapabilitiesProvider.ParseCapabilities(HttpResponse response) in ./Radarr.Core/Indexers/Newznab/NewznabCapabilitiesProvider.cs:line 88
   at NzbDrone.Core.Indexers.Newznab.NewznabCapabilitiesProvider.FetchCapabilities(NewznabSettings indexerSettings) in ./Radarr.Core/Indexers/Newznab/NewznabCapabilitiesProvider.cs:line 67
   at NzbDrone.Core.Indexers.Newznab.NewznabCapabilitiesProvider.<>c__DisplayClass4_0.<GetCapabilities>b__0() in ./Radarr.Core/Indexers/Newznab/NewznabCapabilitiesProvider.cs:line 34
   at NzbDrone.Common.Cache.Cached`1.Get(String key, Func`1 function, Nullable`1 lifeTime) in ./Radarr.Common/Cache/Cached.cs:line 99
   at NzbDrone.Core.Indexers.Newznab.NewznabCapabilitiesProvider.GetCapabilities(NewznabSettings indexerSettings) in ./Radarr.Core/Indexers/Newznab/NewznabCapabilitiesProvider.cs:line 36
   at NzbDrone.Core.Indexers.Torznab.Torznab.get_PageSize() in ./Radarr.Core/Indexers/Torznab/Torznab.cs:line 23
   at NzbDrone.Core.Indexers.Torznab.Torznab.GetRequestGenerator() in ./Radarr.Core/Indexers/Torznab/Torznab.cs:line 27
   at NzbDrone.Core.Indexers.HttpIndexerBase`1.TestConnection() in ./Radarr.Core/Indexers/HttpIndexerBase.cs:line 341
RequestUri: http://IPADDRESS/radarr/prowlarr/5?t=caps&apikey=(removed) OK;ContentLength: 1839;ContentSample: <!doctype html><html lang="en"><head><meta charset="utf-8"/><meta name="viewport" content="width=device-width,initial-scale=1"/><meta name="mobile-web-app-capable" content="yes"/><meta name="apple-mobile-web-app-capable" content="yes"/><meta name="theme-color" content="#e66001"/><meta name="msapplication-navbutton-color" content="#3a3f51"/><meta name="description" content="Prowlarr"/><link rel="apple-touch-icon" sizes="180x180" href="/Content/Images/Icons/apple-touch-icon.png?h=6OFTjFECz9UsB7H/TlShUg"/><link rel="icon" type="image/png" sizes="32x32" href="/Content/Images/Icons/favicon-32x32.png?h=lmqCw7GaBq+Sl0mzceEopQ"/><link rel="icon" type="image/png" sizes="16x16" href="/Content/Images/Icons/favicon-16x16.png?h=eoRdw1mTmIIEK5L0pTH5mw"/><link rel="manifest" href="/Content/Images/Icons/manifest.json?h=cMvkdTsMtUMo5Q+xA1t38g" crossorigin="use-credentials"/><link rel="mask-icon" href="/Content/Images/Icons/safari-pinned-tab.svg?h=D8kxvQdNZQhWkyStrIiagA" color="#00ccff"/><link rel="shortcut icon" type="image/ico" href="/favicon.ico"/><meta name="msapplication-config" content="/Content/Images/Icons/browserconfig.xml"/><link rel="stylesheet" href="/Content/Fonts/fonts.css?h=mBv1x1/yHnvphLclzeQIBA"><script>window.Prowlarr = {
        urlBase: ''
      };</script><script src="/index-4f03fe06b508af5f12a9.js"></script><link href="/Content/styles.css?h=VAwjWra8YBWH8JiyE7JFDA" rel="stylesheet"><title>Prowlarr</title><style>.root {
        overflow: hidden;
        height: 100%; /* needed for proper layout */
      }

**Comment by LuckyPuppy514** [comment]
描述與截圖不一致，看截圖應該是無法連接到這個站點，Radarr 已經正常連接了
看日志應該是Prowlarr 或這個站點有問題，而不是 JProxy 的問題
建議先嘗試把下圖中的 URL 改回 Prowlarr 原始地址后嘗試連接，如果同樣的問題，則證明是 Prowlarr 或這個站點有問題

![image](https://github.com/LuckyPuppy514/jproxy/assets/53246532/63e9bfe3-1139-4c15-846a-1dfe9d2ace47)
