### ISSUE TITLE
Unable to connect to indexer, possibly due to a timeout

### ISSUE THREAD

**Issue by kristianvmd** [LuckyPuppy514/jproxy#62]
sonarr很多索引器连不上

Unable to connect to indexer, possibly due to a timeout. http://192.168.188.188:23117/sonarr/jackett/api/v2.0/indexers/discfan/results/torznab/api?t=tvsearch&cat=5000,5060,5070,5080,100411,100413,100416,100419&extended=1&apikey=(removed)&offset=0&limit=100: The operation was canceled.

System.Threading.Tasks.TaskCanceledException: The operation was canceled.
 ---> System.IO.IOException: Unable to read data from the transport connection: Connection aborted.
 ---> System.Net.Sockets.SocketException (103): Connection aborted
   at System.Net.Sockets.NetworkStream.Read(Span`1 buffer)
   --- End of inner exception stack trace ---
   at System.Net.Sockets.NetworkStream.Read(Span`1 buffer)
   at System.Net.Http.HttpConnection.InitialFillAsync(Boolean async)
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpClient.HandleFailure(Exception e, Boolean telemetryStarted, HttpResponseMessage response, CancellationTokenSource cts, CancellationToken cancellationToken, CancellationTokenSource pendingRequestsCts)
   at System.Net.Http.HttpClient.Send(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationToken cancellationToken)
   at NzbDrone.Common.Http.Dispatchers.ManagedHttpDispatcher.GetResponse(HttpRequest request, CookieContainer cookies) in ./Sonarr.Common/Http/Dispatchers/ManagedHttpDispatcher.cs:line 101
   at NzbDrone.Common.Http.HttpClient.ExecuteRequest(HttpRequest request, CookieContainer cookieContainer) in ./Sonarr.Common/Http/HttpClient.cs:line 141
   at NzbDrone.Common.Http.HttpClient.Execute(HttpRequest request) in ./Sonarr.Common/Http/HttpClient.cs:line 59
   at NzbDrone.Core.Indexers.HttpIndexerBase`1.FetchIndexerResponse(IndexerRequest request) in ./Sonarr.Core/Indexers/HttpIndexerBase.cs:line 351
   at NzbDrone.Core.Indexers.HttpIndexerBase`1.FetchPage(IndexerRequest request, IParseIndexerResponse parser) in ./Sonarr.Core/Indexers/HttpIndexerBase.cs:line 336
   at NzbDrone.Core.Indexers.HttpIndexerBase`1.FetchReleases(Func`2 pageableRequestChainSelector, Boolean isRecent) in ./Sonarr.Core/Indexers/HttpIndexerBase.cs:line 160

**Comment by LuckyPuppy514** [comment]
请按模板格式提问：[问题模板](https://github.com/LuckyPuppy514/jproxy/issues/new/choose)

**Comment by kristianvmd** [comment]
这个格式对不对 我改好了

**Comment by LuckyPuppy514** [comment]
> 这个格式对不对 我改好了

不对，请严格按照模板提示

1. 描述过于简单，请说清楚到底什么站点连不上，报了什么错误
2. 日志提供错误，你这应该是 sonarr 的日志，我需要你提供 JProxy 的日志，问题模板就有提取日志的办法
3. 最好附上相关截图：sonarr 索引器页面的截图，JProxy 配置的截图，Jackett 索引器测试截图

**Comment by LuckyPuppy514** [comment]
按照上述提示改好后，重开问题即可
PS: 照你当前描述，我猜测更有可能是你的网络有问题，请优先检查 Jackett 中索引器测试是否能通过，以及 JProxy 设置是否有问题

**Comment by WoodC2011** [comment]
晚点我再重开一个 
我网络没问题的一直用jproxy的，只是我把sonarr从4.0.0.625更新到4.0.0.629 就很多索引器报错 测试下又好了，过个几分钟又不行了，jackett里都是好的很稳定

**Comment by kristianvmd** [comment]
晚点我再重开，sonarr v4.0.0.621就没这个报错，更新到v4.0.0.625就开始报错了，jackett里测试过没报错

**Comment by LuckyPuppy514** [comment]
![image](https://github.com/LuckyPuppy514/jproxy/assets/53246532/e09bdf37-c903-410a-bead-2011654061ae)
![image](https://github.com/LuckyPuppy514/jproxy/assets/53246532/775dc26d-af69-4801-ac21-06f118010a9a)
