### ISSUE TITLE
sonarr隔个几十分钟，就会挂掉大部分站点

### ISSUE THREAD

**Issue by PlanZV** [LuckyPuppy514/jproxy#73]
**部署环境（windows / docker）**

docker

**问题描述**

sonarr隔个几十分钟，就会挂掉大部分站点，状态一堆报错，点一下检测等个几分钟又会恢复...然后循环...我截了jproxy的日志里跟Jackett相关的日志

**相关日志**

```
13:49:13.346 ERROR [c-593] org.apache.juli.logging.DirectJDKLog.log(DirectJDKLog.java:175)                  : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception
org.springframework.web.client.HttpClientErrorException$TooManyRequests: 429 Too Many Requests: "<?xml version="1.0" encoding="UTF-8"?><EOL><error code="429" description="Indexer is disabled till 09/24/2023 09:14:33 due to recent failures." />"
        at org.springframework.web.client.HttpClientErrorException.create(HttpClientErrorException.java:130) ~[spring-web-6.0.7.jar:6.0.7]
        at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:183) ~[spring-web-6.0.7.jar:6.0.7]
        at org.springframework.web.client.ExtractingResponseErrorHandler.handleError(ExtractingResponseErrorHandler.java:148) ~[spring-web-6.0.7.jar:6.0.7]
        at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:137) ~[spring-web-6.0.7.jar:6.0.7]
        at org.springframework.web.client.ResponseErrorHandler.handleError(ResponseErrorHandler.java:63) ~[spring-web-6.0.7.jar:6.0.7]
        at org.springframework.web.client.RestTemplate.handleResponse(RestTemplate.java:915) ~[spring-web-6.0.7.jar:6.0.7]
        at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:864) ~[spring-web-6.0.7.jar:6.0.7]
        at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:764) ~[spring-web-6.0.7.jar:6.0.7]
        at org.springframework.web.client.RestTemplate.getForEntity(RestTemplate.java:405) ~[spring-web-6.0.7.jar:6.0.7]
        at com.lckp.jproxy.service.impl.IndexerServiceImpl.executeNewRequest(IndexerServiceImpl.java:164) ~[classes/:3.4.0]
        at jdk.internal.reflect.GeneratedMethodAccessor63.invoke(Unknown Source) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
        at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:343) ~[spring-aop-6.0.7.jar:6.0.7]
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:698) ~[spring-aop-6.0.7.jar:6.0.7]
        at com.lckp.jproxy.service.impl.SonarrProwlarrServiceImpl$$SpringCGLIB$$0.executeNewRequest(<generated>) ~[classes/:3.4.0]
        at com.lckp.jproxy.filter.IndexerFilter.doFilter(IndexerFilter.java:114) ~[classes/:3.4.0]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174) ~[tomcat-embed-core-10.1.7.jar:10.1.7]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149) ~[tomcat-embed-core-10.1.7.jar:10.1.7]
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:166) ~[tomcat-embed-core-10.1.7.jar:10.1.7]
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90) ~[tomcat-embed-core-10.1.7.jar:10.1.7]
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:493) ~[tomcat-embed-core-10.1.7.jar:10.1.7]
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:115) ~[tomcat-embed-core-10.1.7.jar:10.1.7]
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93) ~[tomcat-embed-core-10.1.7.jar:10.1.7]
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74) ~[tomcat-embed-core-10.1.7.jar:10.1.7]
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:341) ~[tomcat-embed-core-10.1.7.jar:10.1.7]
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:390) ~[tomcat-embed-core-10.1.7.jar:10.1.7]
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63) ~[tomcat-embed-core-10.1.7.jar:10.1.7]
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:894) ~[tomcat-embed-core-10.1.7.jar:10.1.7]
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1741) ~[tomcat-embed-core-10.1.7.jar:10.1.7]
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52) ~[tomcat-embed-core-10.1.7.jar:10.1.7]
        at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191) ~[tomcat-embed-core-10.1.7.jar:10.1.7]
        at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659) ~[tomcat-embed-core-10.1.7.jar:10.1.7]
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) ~[tomcat-embed-core-10.1.7.jar:10.1.7]
        at java.lang.Thread.run(Unknown Source) ~[?:?]
13:50:48.664 ERROR [c-599] xy.controller.SystemConfigController.listAuthor(SystemConfigController.java:107) : 获取作者列表出错：I/O error on GET request for "https://raw.githubusercontent.com/LuckyPuppy514/jproxy/main/src/main/resources/rule/author.json": Connection refused
14:00:00.667 INFO  [ing-1] jproxy.service.impl.SonarrTitleServiceImpl.sync(SonarrTitleServiceImpl.java:150) : 同步剧集标题成功：321
14:00:03.491 INFO  [ing-1] ckp.jproxy.service.impl.TmdbTitleServiceImpl.sync(TmdbTitleServiceImpl.java:127) : 同步剧集标题成功：0
14:05:13.862 ERROR [c-600] org.apache.juli.logging.DirectJDKLog.log(DirectJDKLog.java:175)                  : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception
org.springframework.web.client.HttpClientErrorException$TooManyRequests: 429 Too Many Requests: "<?xml version="1.0" encoding="UTF-8"?><EOL><error code="429" description="Indexer is disabled till 09/23/2023 14:34:12 due to recent failures." />"
        at org.springframework.web.client.HttpClientErrorException.create(HttpClientErrorException.java:130) ~[spring-web-6.0.7.jar:6.0.7]
        at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:183) ~[spring-web-6.0.7.jar:6.0.7]
        at org.springframework.web.client.ExtractingResponseErrorHandler.handleError(ExtractingResponseErrorHandler.java:148) ~[spring-web-6.0.7.jar:6.0.7]
        at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:137) ~[spring-web-6.0.7.jar:6.0.7]
        at org.springframework.web.client.ResponseErrorHandler.handleError(ResponseErrorHandler.java:63) ~[spring-web-6.0.7.jar:6.0.7]
        at org.springframework.web.client.RestTemplate.handleResponse(RestTemplate.java:915) ~[spring-web-6.0.7.jar:6.0.7]
        at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:864) ~[spring-web-6.0.7.jar:6.0.7]
        at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:764) ~[spring-web-6.0.7.jar:6.0.7]
        at org.springframework.web.client.RestTemplate.getForEntity(RestTemplate.java:405) ~[spring-web-6.0.7.jar:6.0.7]
        at com.lckp.jproxy.service.impl.IndexerServiceImpl.executeNewRequest(IndexerServiceImpl.java:164) ~[classes/:3.4.0]
        at jdk.internal.reflect.GeneratedMethodAccessor63.invoke(Unknown Source) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
        at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:343) ~[spring-aop-6.0.7.jar:6.0.7]
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:698) ~[spring-aop-6.0.7.jar:6.0.7]
        at com.lckp.jproxy.service.impl.SonarrProwlarrServiceImpl$$SpringCGLIB$$0.executeNewRequest(<generated>) ~[classes/:3.4.0]
        at com.lckp.jproxy.filter.IndexerFilter.doFilter(IndexerFilter.java:114) ~[classes/:3.4.0]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174) ~[tomcat-embed-core-10.1.7.jar:10.1.7]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149) ~[tomcat-embed-core-10.1.7.jar:10.1.7]
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:166) ~[tomcat-embed-core-10.1.7.jar:10.1.7]
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90) ~[tomcat-embed-core-10.1.7.jar:10.1.7]
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:493) ~[tomcat-embed-core-10.1.7.jar:10.1.7]
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:115) ~[tomcat-embed-core-10.1.7.jar:10.1.7]
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93) ~[tomcat-embed-core-10.1.7.jar:10.1.7]
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74) ~[tomcat-embed-core-10.1.7.jar:10.1.7]
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:341) ~[tomcat-embed-core-10.1.7.jar:10.1.7]
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:390) ~[tomcat-embed-core-10.1.7.jar:10.1.7]
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63) ~[tomcat-embed-core-10.1.7.jar:10.1.7]
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:894) ~[tomcat-embed-core-10.1.7.jar:10.1.7]
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1741) ~[tomcat-embed-core-10.1.7.jar:10.1.7]
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52) ~[tomcat-embed-core-10.1.7.jar:10.1.7]
        at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191) ~[tomcat-embed-core-10.1.7.jar:10.1.7]
        at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659) ~[tomcat-embed-core-10.1.7.jar:10.1.7]
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) ~[tomcat-embed-core-10.1.7.jar:10.1.7]
        at java.lang.Thread.run(Unknown Source) ~[?:?]
14:26:26.075 ERROR [c-596] org.apache.juli.logging.DirectJDKLog.log(DirectJDKLog.java:175)                  : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception
org.springframework.web.client.HttpClientErrorException$BadRequest: 400 Bad Request: "<?xml version="1.0" encoding="UTF-8"?><EOL><error code="900" description="Jackett.Common.IndexerException: Exception (hdtime): Request to https://hdtime.org/torrents.php?cat424=1&amp;cat402=1&amp;cat403=1&amp;cat405=1&amp;cat407=1&amp;cat404=1&amp;cat406=1&amp;cat408=1&amp;incldead=0&amp;spstate=0&amp;search_area=0&amp;search_mode=0&amp;sort=4&amp;type=desc&amp;notnewword=1 failed (Error 522) - The tracker seems to be down.&#xA; ---&gt; System.Exception: Request to https://hdtime.org/torrents.php?cat424=1&amp;cat402=1&amp;cat403=1&amp;cat405=1&amp;cat407=1&amp;cat404=1&amp;cat406=1&amp;cat408=1&amp;incldead=0&amp;spstate=0&amp;search_area=0&amp;search_mode=0&amp;sort=4&amp;type=desc&amp;notnewword=1 failed (Error 522) - The tracker seems to be down.&#xA;   at Jackett.Common.Indexers.BaseWebIndexer.CheckSiteDown(WebResult response) in ./Jackett.Common/Indexers/BaseIndexer.cs:line 579&#xA;   at Jackett.Common.Indexers.BaseWebIndexer.RequestWithCookiesAsync(String url, String cookieOverride, RequestType method, String referer, IEnumerable`1 data, Dictionary`2 headers, String rawbody, Nullable`1 emulateBrowser) in ./Jackett.Common/Indexers/BaseIndexer.cs:line 535&#xA;   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in ./Jackett.Common/Indexers/CardigannIndexer.cs:line 1505&#xA;   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in ./Jackett.Common/Indexers/BaseIndexer.cs:line 332&#xA;   --- End of inner exception stack trace ---&#xA;   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in ./Jackett.Common/Indexers/BaseIndexer.cs:line 332&#xA;   at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in ./Jackett.Common/Indexers/BaseIndexer.cs:line 709&#xA;   at Jackett.Server.Controllers.ResultsController.Torznab(TorznabRequest request) in ./Jackett.Server/Controllers/ResultsController.cs:line 469" />"
        at org.springframework.web.client.HttpClientErrorException.create(HttpClientErrorException.java:103) ~[spring-web-6.0.7.jar:6.0.7]
        at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:183) ~[spring-web-6.0.7.jar:6.0.7]
        at org.springframework.web.client.ExtractingResponseErrorHandler.handleError(ExtractingResponseErrorHandler.java:148) ~[spring-web-6.0.7.jar:6.0.7]
        at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:137) ~[spring-web-6.0.7.jar:6.0.7]
        at org.springframework.web.client.ResponseErrorHandler.handleError(ResponseErrorHandler.java:63) ~[spring-web-6.0.7.jar:6.0.7]
        at org.springframework.web.client.RestTemplate.handleResponse(RestTemplate.java:915) ~[spring-web-6.0.7.jar:6.0.7]
        at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:864) ~[spring-web-6.0.7.jar:6.0.7]
        at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:764) ~[spring-web-6.0.7.jar:6.0.7]
        at org.springframework.web.client.RestTemplate.getForEntity(RestTemplate.java:405) ~[spring-web-6.0.7.jar:6.0.7]
        at com.lckp.jproxy.service.impl.IndexerServiceImpl.executeNewRequest(IndexerServiceImpl.java:164) ~[classes/:3.4.0]
        at jdk.internal.reflect.GeneratedMethodAccessor63.invoke(Unknown Source) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
        at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:343) ~[spring-aop-6.0.7.jar:6.0.7]
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:698) ~[spring-aop-6.0.7.jar:6.0.7]
        at com.lckp.jproxy.service.impl.SonarrJackettServiceImpl$$SpringCGLIB$$0.executeNewRequest(<generated>) ~[classes/:3.4.0]
        at com.lckp.jproxy.filter.IndexerFilter.doFilter(IndexerFilter.java:114) ~[classes/:3.4.0]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174) ~[tomcat-embed-core-10.1.7.jar:10.1.7]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149) ~[tomcat-embed-core-10.1.7.jar:10.1.7]
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:166) ~[tomcat-embed-core-10.1.7.jar:10.1.7]
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90) ~[tomcat-embed-core-10.1.7.jar:10.1.7]
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:493) ~[tomcat-embed-core-10.1.7.jar:10.1.7]
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:115) ~[tomcat-embed-core-10.1.7.jar:10.1.7]
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93) ~[tomcat-embed-core-10.1.7.jar:10.1.7]
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74) ~[tomcat-embed-core-10.1.7.jar:10.1.7]
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:341) ~[tomcat-embed-core-10.1.7.jar:10.1.7]
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:390) ~[tomcat-embed-core-10.1.7.jar:10.1.7]
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63) ~[tomcat-embed-core-10.1.7.jar:10.1.7]
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:894) ~[tomcat-embed-core-10.1.7.jar:10.1.7]
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1741) ~[tomcat-embed-core-10.1.7.jar:10.1.7]
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52) ~[tomcat-embed-core-10.1.7.jar:10.1.7]
        at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191) ~[tomcat-embed-core-10.1.7.jar:10.1.7]
        at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659) ~[tomcat-embed-core-10.1.7.jar:10.1.7]
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) ~[tomcat-embed-core-10.1.7.jar:10.1.7]
```

**Comment by PlanZV** [comment]
实际jackett里都是通的，几乎没报错的站点

**Comment by LuckyPuppy514** [comment]
看日志这个站点，是你请求太频繁被站点屏蔽了
其他要确保 jackett 重新检测正常才行，绿色不一定是当前状态，是隔一段时间更新的
还有 jproxy 有缓存，站点状态也需要一段时间更新
我这边并没有你说的全部挂掉的情况，这种情况更有可能是你的网络不稳定造成的

**Comment by PlanZV** [comment]
好的，不过我radarr那边一直都是正常的，只是sonarr用了jproxy以后就这样了，而且jproxy上一个版本是没事的，我一周前升级到最新版就开始这样反复报错了，重装也试过都没用、至于网络的话，我这家机场很老了很稳定的，RSS更新我也设置的是一个小时才获取一次

**Comment by PlanZV** [comment]
我等了一周，确认是反复出现这个问题，状态的话我点一下测试全部索引器一小会就都好了，但是等一个小时又开始一堆出错，同时间我检查radarr是没问题的，两边加的索引器是一模一样的

**Comment by LuckyPuppy514** [comment]
![image](https://github.com/LuckyPuppy514/jproxy/assets/53246532/bdb6e51b-2e49-49a6-b00a-3a11bbbaae75)

我这边没这个问题，你提供的日志也是源站报的访问限制

**Comment by PlanZV** [comment]
我系统不是群晖和威联通这种成品NAS，会不会是docker本身缺个组件之类造成的，因为上个版本没事....我实在想不到别的原因了

**Comment by LuckyPuppy514** [comment]
没法复现问题不好定位，要不你加下Q群：921905633 找我，我远程看看

**Comment by PlanZV** [comment]
十一忘了这事了~~sonarr后来升级了个版本，就没事了
